# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_key', models.IntegerField()),
                ('anon_user_id', models.IntegerField()),
                ('text', models.TextField()),
                ('course_id', models.IntegerField()),
                ('instructor_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_key', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('section', models.FloatField(verbose_name='format xxx.xxx')),
                ('year', models.PositiveSmallIntegerField(verbose_name='format xxxx')),
                ('semester', models.CharField(choices=[('1', 'Spring'), ('2', 'Summer'), ('3', 'Fall')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_key', models.IntegerField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_key', models.IntegerField()),
                ('query', models.TextField()),
                ('result', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Stopword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_key', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
