# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='../media/downloads')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Json_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FilePathField(match='.*\\.csv$', path='/Users/akh/Desktop/CADET_Sandbox/cadetapp/media/downloads/')),
                ('comments', models.PositiveIntegerField()),
                ('topics', models.PositiveIntegerField()),
                ('iterations', models.PositiveIntegerField()),
            ],
        ),
    ]
